version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: busca_cep_postgres
    environment:
      POSTGRES_DB: busca_cep_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - busca_cep_network

volumes:
  postgres_data:

networks:
  busca_cep_network:
    driver: bridge
